#!/usr/bin/env python3
"""Build an isolated, instrumented copy of Trouble In Armaville for QA."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import stat
import xml.etree.ElementTree as ET
from pathlib import Path


HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
MISSION_ITEMS = (
    "audio",
    "functions",
    "ui",
    "config.sqf",
    "description.ext",
    "init.sqf",
    "initPlayerLocal.sqf",
    "mission.sqm",
    "onPlayerRespawn.sqf",
    "stringtable.xml",
)
QA_SQF = ("qaCommon.sqf", "qaBootstrap.sqf", "runUiAudit.sqf", "runRoundAudit.sqf")


PLACEHOLDER = re.compile(r"%\d+")


def stringtable_keys(path: Path, languages: list[str], canonical_fallbacks: list[str]) -> list[str]:
    root = ET.parse(path).getroot()
    keys: list[str] = []
    seen: set[str] = set()
    for node in root.iter("Key"):
        key = node.attrib["ID"]
        if key in seen:
            raise ValueError(f"Duplicate stringtable key: {key}")
        seen.add(key)
        keys.append(key)
        values = {child.tag: child.text or "" for child in node}
        english = values.get("English", "")
        required = ["Original", "English"] if key in canonical_fallbacks else ["Original", *languages]
        for language in required:
            if not values.get(language, "").strip():
                raise ValueError(f"{key} has no non-empty <{language}> translation")
            if sorted(PLACEHOLDER.findall(values[language])) != sorted(PLACEHOLDER.findall(english)):
                raise ValueError(f"{key} <{language}> does not preserve English placeholders")
    return sorted(keys)


def sqf_array(values: list[str]) -> str:
    return "[" + ",".join(json.dumps(value) for value in values) + "]"


def guarded_destination(destination: Path) -> Path:
    destination = destination.resolve()
    if destination.name != "TTT_Localisation_Gameplay_Audit.Altis":
        raise ValueError("Destination must end in TTT_Localisation_Gameplay_Audit.Altis")
    if destination.parent.name.lower() != "missions":
        raise ValueError("Destination must be directly below an Arma 3 Missions directory")
    return destination


def remove_readonly(function, path: str, _error) -> None:
    """Allow a disposable rebuild when Windows copied a read-only attribute."""
    os.chmod(path, stat.S_IWRITE)
    function(path)


def build(destination: Path, language: str) -> None:
    destination = guarded_destination(destination)
    manifest = json.loads((HERE / "audit_manifest.json").read_text(encoding="utf-8"))
    if language not in manifest["languages"]:
        raise ValueError(f"Unsupported language: {language}")

    if destination.exists():
        # onerror is available on every supported Python 3 version; onexc
        # would make the contributor harness require Python 3.12 or newer.
        shutil.rmtree(destination, onerror=remove_readonly)
    destination.mkdir(parents=True)
    for item in MISSION_ITEMS:
        source = REPO / item
        target = destination / item
        if source.is_dir():
            shutil.copytree(source, target)
        else:
            shutil.copy2(source, target)

    qa_dir = destination / "qa"
    qa_dir.mkdir()
    for name in QA_SQF:
        shutil.copy2(HERE / "mission" / name, qa_dir / name)

    description = destination / "description.ext"
    description.write_text(
        description.read_text(encoding="utf-8").rstrip()
        + "\n\n// Disposable playMission audit: do not wait for a manual briefing Continue click.\nbriefing = 0;\n",
        encoding="utf-8",
    )

    keys = stringtable_keys(
        REPO / "stringtable.xml", manifest["languages"], manifest["canonicalFallbackKeys"]
    )
    captures = [entry["id"] for entry in manifest["captures"]]
    (qa_dir / "auditConfig.sqf").write_text(
        "// Generated by build_audit_mission.py; do not edit.\n"
        f'TTT_QA_Language = {json.dumps(language)};\n'
        f"TTT_QA_StringKeys = {sqf_array(keys)};\n"
        f"TTT_QA_ExpectedCaptures = {sqf_array(captures)};\n",
        encoding="utf-8",
    )

    client_init = destination / "initPlayerLocal.sqf"
    client_init.write_text(
        client_init.read_text(encoding="utf-8").rstrip()
        + '\n\n// Disposable localisation/gameplay audit hook.\n[] execVM "qa\\qaBootstrap.sqf";\n',
        encoding="utf-8",
    )
    server_init = destination / "init.sqf"
    server_source = server_init.read_text(encoding="utf-8").rstrip()
    server_init.write_text(
        '// Disposable playMission fallback: multiplayer normally defines paramsArray.\n'
        'if (isNil "paramsArray") then { paramsArray = []; };\n\n'
        + server_source
        + '\n\n// Disposable localisation/gameplay audit hook.\nif (isServer) then { [] execVM "qa\\runRoundAudit.sqf"; };\n',
        encoding="utf-8",
    )

    build_manifest = {
        "schemaVersion": manifest["schemaVersion"],
        "source": str(REPO),
        "language": language,
        "stringtableKeyCount": len(keys),
        "captures": captures,
        "roundChecks": manifest["roundChecks"],
        "sourceItems": list(MISSION_ITEMS),
    }
    (destination / "qa_build_manifest.json").write_text(
        json.dumps(build_manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Built {destination} for {language}: {len(keys)} keys, {len(captures)} captures")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--destination", type=Path, required=True)
    parser.add_argument("--language", required=True)
    args = parser.parse_args()
    build(args.destination, args.language)


if __name__ == "__main__":
    main()
